# Generated by Django 4.1.7 on 2023-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasklist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
